### ISSUE TITLE
Bug: Crash on Autocomplete in Snowflake SQL

### ISSUE THREAD

**Issue by sinklair** [hankinsoft/SQLPro#1088]
### Describe the bug

**Describe the bug**
Authoring a query against a snowflake database, when autocomplete shows a series of views and I try to select a view name, the app crashes.

**To Reproduce**
1. Connect to Snowflake
2. Double-click a view to open default statement
3. Add an inner join to another table and wait for autocomplete to display
4. Select a view from the list

**Expected behavior**
Autocomplete fills in the view name

**Screenshots**
App crash

**Additional details**
Version 2025.76
No crash when autocompleting column names.

### Product

SQLPro Studio

### App version

111152.5

### Platform

macOS

### Installation source

App Store

**Comment by hankinsoft** [comment]
Hi.
I've been working on a big update for Snowflake.

The connector has been rebuilt on a new native engine, and as part of
that a lot of long-standing requests and bugs have been addressed. Highlights:

New ways to sign in
- Key-pair (JWT) authentication
- Programmatic Access Tokens (PAT)
- OAuth
- Username/password with MFA
- External-browser SSO — works with Okta, Microsoft / Azure AD, and other SAML
  identity providers (this is the "open your browser to log in" flow)
- Proxy support in the connection's Advanced settings (host/port/user/password)

Fixes & reliability
- Correct "rows inserted / updated" counts are now reported after running DML.
- Inserting and editing rows in the results grid works reliably again (an
  internal crash on insert has been fixed).
- Addressed a crash some of you hit during autocomplete — this should be
  resolved now. If you still run into it, please let us know.
- Table-designer column changes (rename, change type, nullability, default) now
  generate valid Snowflake SQL.
- More reliable connecting, database/schema browsing, and result streaming
  overall.

If you have a moment to update and confirm this works for your setup, we'd
really appreciate the feedback. Thanks for your patience and for the detailed
reports that made these fixes possible!

The new build is available at:
https://d3fwkemdw8spx3.cloudfront.net/temp/SQLProSnowflake.2026.165.app.zip

**Comment by sinklair** [comment]
Is there a SQLPro Studio version of the update?

**Comment by sinklair** [comment]
@hankinsoft I tested this version with the 7 day trial and still seeing the same issue. Anytime I use Autocomplete to fill in a table or view name in the SQL editor, the app crashes.

**Comment by hankinsoft** [comment]
New update to try here if possible:
https://d3fwkemdw8spx3.cloudfront.net/temp/SQLProSnowflake.2026.169.app.zip

If this version still crashes, could you possibly provide the crash log? You should be able to navigate to ~/Library/Logs/DiagnosticReports/ and grab it from there.

I'll get a studio build up and running once I have all the snowflake kinks worked out.

**Comment by sinklair** [comment]
Sorry for the late response - that fixed the issue!

**Comment by hankinsoft** [comment]
Oh nice! I'm going to mark this one as fixed then 👍
