### ISSUE TITLE
Feature Request: Basic per-statement stats

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#491]
It'd be really handy to have some basic per-statement stats like number of rows affected and execution time (and maybe 1-2 others you may think helpful) when running multiple at a time

![image](https://user-images.githubusercontent.com/15026225/92154095-7c2df580-ede2-11ea-908d-0e4987eca6a0.png)

I'm thinking they could display immediately after each message. So maybe the first line would instead say:
"Statement executed successfully. (Line 1). 0 rows affected. .89 seconds."
or something like that

SQLPro Studio 2020.75 (Build 110709.5)
macOS 10.15.6 (19G2021)

**Comment by hankinsoft** [comment]
This is partially implemented. Issue #512 is an issue relating to this feature:

> I noticed that only "Initializing connection..." showed until after the full query executed, making it appear for 12.9 seconds (the full duration) that it was taking 12 seconds to establish connection, even though that part only took .07 seconds.
>
> Loving that these times now display, though. Very helpful!
>
> macOS 10.15.7 (19H2)
> SQLPro Studio 2020.88 (Build 110729.5)
> Snowflake 4.33.1

**Comment by jim256** [comment]
I really like this. It's been nice to see how long each step takes.
If it's available, I'd like to also have the number of rows affected by each statement.

**Comment by hankinsoft** [comment]
> I really like this. It's been nice to see how long each step takes.
> If it's available, I'd like to also have the number of rows affected by each statement.

That should already display. Could you send a screenshot showing a query and the 'result messages' NOT displaying the rows affected?

**Comment by jim256** [comment]
Looks like it outputs records for select statements, but not for others (creating temp tables in this example here):

<img width="868" alt="image" src="https://user-images.githubusercontent.com/15026225/100132657-f6e73980-2e42-11eb-820c-39eb95f33ee2.png">

Log:
[com.hankinsoft.osx.sqlprostudio 2020-11-24--17-48-04-041.log](https://github.com/hankinsoft/SQLPro/files/5591776/com.hankinsoft.osx.sqlprostudio.2020-11-24--17-48-04-041.log)


SQLPro Studio 2020.102 (Build 110758.5)
macOS 11.0.1 (20B29)
Snowflake 4.39.5

**Comment by hankinsoft** [comment]
What syntax are you using to create your tables?

**Comment by jim256** [comment]
I'm using:

`CREATE OR REPLACE TEMP TABLE [table_name] AS

SELECT ....
;
`

**Comment by hankinsoft** [comment]
Fixed for the next build (2021.06) Should be available later this week or early next.

<img width="1382" alt="Screen Shot 2021-01-27 at 1 56 52 PM" src="https://user-images.githubusercontent.com/3160528/106033024-9aed9b00-60a7-11eb-94d1-917ce7014baf.png">

**Comment by jim256** [comment]
This will definitely be handy.

**Comment by jim256** [comment]
FWIW, #512 is still happening for me in 2021.05 (Build 110767.5).

**Comment by jim256** [comment]
Forgot this build was out. When I create a temp table with 589 rows, it's showing the following for me:
`Table TEMP_TABLE successfully created. (1 rows affected) 1.757 seconds. (Line 4).`

<img width="499" alt="image" src="https://user-images.githubusercontent.com/15026225/107070558-bee46700-67a0-11eb-91a0-5777cc3ef0cd.png">

SQLPro Studio 2021.10 (Build 110772.5)
macOS 11.1 (20C69)
Snowflake 5.3.1

**Comment by hankinsoft** [comment]
I've been investigating this a bit further. Unfortunately the snowflake library does not return a row count during a CREATE statement (it returns 1 for the number of rows). I think in this case, it would probably be better to display `Table successfully created` without a row count rather than displaying the `1 row affected` as that could throw off a user. I'm making this change for the next build.

**Comment by hankinsoft** [comment]
> I think in this case, it would probably be better to display Table successfully created without a row count rather than displaying the 1 row affected as that could throw off a user. I'm making this change for the next build.

This should be fixed in the latest build. Other than this, was there anything else I am missing within this issue?

**Comment by hankinsoft** [comment]
Thanks, I knew there was something. For #512:
`I noticed that only "Initializing connection..." showed until after the full query executed`

So basically the `Connection ready. Took xxx seconds` needs to show up earlier?

**Comment by jim256** [comment]
That, and also some of the earlier statements. I think that it'll often skip printing anything except for "Initializing connection..." until it's all done, even if it runs 5 statements. All 5 (and their stats) will just print out at the same time when it finishes.

**Comment by hankinsoft** [comment]
Thanks - I believe I have this sorted in the latest available build. Please give it a try if you get the chance.

**Comment by jim256** [comment]
Seems to be fixed! :muscle:
