### ISSUE TITLE
Crashing with huge sql

### ISSUE THREAD

**Issue by TGit911iger** [hankinsoft/SQLPro#514]
Executing huge sql crashes the app.
[sample.sql.zip](https://github.com/hankinsoft/SQLPro/files/5368689/sample.sql.zip)

**Comment by hankinsoft** [comment]
Investigating this - Is this mysql you are seeing the issue with?

**Comment by hankinsoft** [comment]
Also, what do you have setup for the 'Execute query in cursor range' preference? Is it 'Disabled', 'Enabled', or 'Enabled (as default)'?

**Comment by manngo** [comment]
I have the same problem with a rather large query.

- SQLPro Studio Version 2020.88 (Build 110729.5)
- Using Microsoft SQL connected to a docker image on the lan
- 3340 lines in the script
- Execute query in cursor range: Disabled

[towns.sql.zip](https://github.com/hankinsoft/SQLPro/files/5449168/towns.sql.zip)

If this is not the same issue, I am happy to create a new one.

Thanks

**Comment by hankinsoft** [comment]
I've reproduced using that SQL - thank you! I should have a fix available later this week.

**Comment by hankinsoft** [comment]
FYI the latest fix is all available. If you get the chance, please update and let me know if everything is all good.

**Comment by manngo** [comment]
Thanks, I tried running the same SQL script, but it still crashed.

The version I have is Version 2020.99 (Build 110750.5).

Would the log report normally sent to Apple be of any use? I can attach it if you like.

**Comment by hankinsoft** [comment]
I'm submitting another build now which I think will help sort the issue. If you still see the problem after updating to 2020.100, please let me know. The build will take ~24 hours or so to be approved.

**Comment by hankinsoft** [comment]
2020.100 is now avaiable. If you get the chance, could you give this a try?

**Comment by manngo** [comment]
Works perfectly. I have tried it with my sample script with thousands of INSERT statements, and it did the job.

I haven’t tried a bigger file yet, but I wll later and let you know how it goes.

Thanks as always for your help.
