### ISSUE TITLE
Folder/Table tree not expanding correctly

### ISSUE THREAD

**Issue by realfoz** [hankinsoft/SQLPro#71]
Hey guys,

Having an issue when I expand a table in the tree on the left. After scrolling I can see the folders overlapping with the table items. Screenshot attached.

<img width="445" alt="screen shot 2017-01-24 at 10 49 18 am" src="https://cloud.githubusercontent.com/assets/1767848/22255379/2e0a06ea-e225-11e6-9fa8-0417c1c550a0.png">

**Comment by hankinsoft** [comment]
What product version are you using? Could you possibly post a screenshot of the about dialog?

**Comment by realfoz** [comment]
Hey Kyle,

Yeah sure thing: v 1.0.27 (build 40)

<img width="773" alt="screen shot 2017-02-08 at 2 30 56 pm" src="https://cloud.githubusercontent.com/assets/1767848/22753818/7892d16e-ee0b-11e6-8275-b5f516a79e7b.png">

**Comment by hankinsoft** [comment]
Ah, that explains it. Thats quite an old version (from before I added update notifications :)
99.9% sure that this issue has been resolved in the new version as well. 

Can you grab the latest version here:
https://sqlprostudio.com/download.php

**Comment by realfoz** [comment]
Ah right on - I think it may be because I was using brew cask to install....I'll update and let you know if I still see it.

In the meantime I'll close, thanks for your help. And for a solid piece of software!
