### ISSUE TITLE
Editor replacing quotation marks with typographic ones.

### ISSUE THREAD

**Issue by neongrau** [hankinsoft/SQLPro#72]
I have tried editing a column with HTML content (SQLPro Studio on an MSSQL Database).

entered `<img src="something.png">`.
ended up with broken HTML because it saved `<img src=„something.png“>`

**Comment by hankinsoft** [comment]
Thank you, I have been able to reproduce and resolve the issue. Please let me know which product you are using and I can post a build for you.

**Comment by neongrau** [comment]
i'm using SQLPro Studio 1.0.107 Build 1038 from the App Store

**Comment by hankinsoft** [comment]
I've submitted a new build to the Mac App Store. Generally these are
available within a week although often quite a bit sooner.  Once it's
available I'll write back here, and get you to check and see if it has
resolved.

**Comment by hankinsoft** [comment]
Hi,
The new version is available. Can you confirm if  you are still seeing the issue?

**Comment by neongrau** [comment]
Hi,

while 1.0.111 Description in the App Store updates lists this as a fixed issue.
The 1.0.115 version i'm currently running which arrived a week later is still showing that unwanted behavior.

So not fixed yet.

**Comment by neongrau** [comment]
Thought that issue was fixed.

Just messed up some HTML again in SQLPro Studio 1.0.126 Build 1059 from the App Store 
:(

**Comment by neongrau** [comment]
Hello?

Could you please get this fixed in the App Store version? And please make sure it stays fixed?

**Comment by hankinsoft** [comment]
Hello. I’ll take a look into this in the next week.

**Comment by hankinsoft** [comment]
Hi. The latest App Store version was approved earlier this weekend and has this fix. Can you give it a try and let me know if that sorts the issue you are seeing? Thanks!
